-- language=h2

CREATE TABLE company (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(255),
  company_description CLOB,
  company_website VARCHAR(255),
  country_located VARCHAR(255)
);

CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_title VARCHAR(255),
  job_description CLOB,
  seniority_level VARCHAR(255),
  max_salary VARCHAR(255),
  location VARCHAR(255),
  posting_url VARCHAR(255),
  company_id BIGINT,
  CONSTRAINT FK_job_company FOREIGN KEY (company_id) REFERENCES company(id)
);